### ISSUE TITLE
Winget Releaser workflow is skipped

### ISSUE THREAD

**Issue by sitiom** [jftuga/less-Windows#18]
The Winget Releaser workflow is failing. Just a reminder that you need to do the prerequisites mentioned in https://github.com/jftuga/less-Windows/pull/17#issue-1360765337 and rerun the failed workflow.

**Comment by jftuga** [comment]
I've performed this task.  How is it looking now?

**Comment by sitiom** [comment]
Now the workflow is skipped because the release already exists. Can you delete https://github.com/jftuga/less-Windows/releases/tag/less-v608 to retrigger the Winget workflow?

**Comment by jftuga** [comment]
Run vedantmgoyal2009/winget-releaser@latest
    D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:1115
        throw new Error('Parameter token or opts.auth is required');
                ^

    Error: Parameter token or opts.auth is required
    at Object.getAuthString (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:1115:15)
    at Object.getOctokitOptions (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:1186:24)
    at getOctokit (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:1079:39)
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9699:13
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9780:3
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9782:3
    at Object.<anonymous> (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9785:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

**Comment by sitiom** [comment]
I think rerunning the workflow does not update the tokens of the rerun workflow; you would have to run a new workflow.

**Comment by jftuga** [comment]
I made a small change to `README.md` to trigger a new workflow, but the same error occurred.

**Comment by sitiom** [comment]
That just means you have not inputted the `WINGET_TOKEN` secret in your repo.

**Comment by jftuga** [comment]
Update: I am working on this

**Comment by jftuga** [comment]
I added `WINGET_TOKEN` to the repo and am getting a little bit further.  I now see this error. Please advise.  Also, thank you for working on this and your patience. 

    Install powershell-yaml, clone winget-pkgs and configure remotes, update YamlCreate, download wingetdev...
    fatal: destination path 'winget-pkgs' already exists and is not an empty directory.
    node:child_process:826
        err = new Error(msg);
                ^
    
    Error: Command failed: git clone ***github.com/microsoft/winget-pkgs.git
        at checkExecSyncError (node:child_process:826:11)
        at execSync (node:child_process:900:15)
        at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9716:3
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        status: 128,
        signal: null,
        output: [ null, null, null ],
        pid: 5932,
        stdout: null,
        stderr: null
    }

https://github.com/jftuga/less-Windows/runs/8219725750?check_suite_focus=true

**Comment by jftuga** [comment]
See also: https://github.com/microsoft/winget-pkgs/pull/78816#issuecomment-1238837815

**Comment by sitiom** [comment]
@vedantmgoyal2009 This happens when you run winget releaser more than once:
![image](https://user-images.githubusercontent.com/56180050/188778214-61f1ba92-ec03-41a2-93d6-42c807bbe70b.png)
