### ISSUE TITLE
Remove vcruntime140.dll dependency

### ISSUE THREAD

**Issue by nu8** [jftuga/less-Windows#2]
Currently Less is linked with `vcruntime140.dll`:

~~~
PS C:\> llvm-objdump.exe -p less.exe | ag DLL
DLL Name: USER32.dll
DLL Name: KERNEL32.dll
DLL Name: VCRUNTIME140.dll
~~~

it might be better to link with `ucrtbase.dll` instead, as its preinstalled
with Windows 10.

**Comment by jftuga** [comment]
@nu8 could you please post this issue with the upstream provider?

https://github.com/gwsw/less

I am simply using their `makefile` to provide a Windows binary and building it on `AppVeyor`.

**Comment by nu8** [comment]
They dont provide Windows builds, so I believe this is the appropriate place.

**Comment by jftuga** [comment]
I used `dumpbin.exe /imports less.exe` to see what is used by `vcruntime140.dll`:

    VCRUNTIME140.dll
             14001B168 Import Address Table
             140022FF8 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                          40 strchr
                          3E memset
                          3C memcpy
                          3A memchr
                          1D __intrinsic_setjmp
                           8 __C_specific_handler
                          1B __current_exception
                          1C __current_exception_context

Would any source code need changing or just the `Makefile`?  If the latter, what would need to change?

This is what is currently used:

https://github.com/gwsw/less/blob/master/Makefile.wnm

**Comment by nu8** [comment]
Hm, it might not be possible at this time, depending on what functions are used:

https://stackoverflow.com/questions/61375024

**Comment by jftuga** [comment]
I removed `/MD` from the `CFLAGS` in the Makefile.  I have a beta binary which does not list `vcruntime140.dll` with `dumpbin.exe`.  Can you please:

* Check it against `llvm-objdump.exe`
* Actually run this binary to make sure it still properly runs as expected:
* https://github.com/jftuga/less-Windows/releases/tag/less-v562.1

**Comment by nu8** [comment]
Seems to run same as before, `llvm-objdump.exe` reports this:

~~~
DLL Name: USER32.dll
DLL Name: KERNEL32.dll
~~~

looks good!

**Comment by jftuga** [comment]
Does this binary seem to work OK for you?

**Comment by nu8** [comment]
I only did a `git diff`, but it seems to work same as before

**Comment by jftuga** [comment]
I will submit an issue with the upstream repo and ask for this change.

**Comment by jftuga** [comment]
The upstream maintainer has created a PR for this:

https://github.com/gwsw/less/commit/329b2150bf9814dc17314fcf490205cc9ba3e512

Once a new official version is released (probably v563), then my binaries will include this fix as well.
