### ISSUE TITLE
Mouse scrolling no longer works on less 608

### ISSUE THREAD

**Issue by nathpete-msft** [jftuga/less-Windows#23]
After updating to less 608 mouse scrolling is no longer working, and worked fine on 590.

## Repro Steps

- Open any of: cmd, PowerShell (Windows or Core), Windows Terminal
- Run `less --mouse --help`
- Try scrolling with the mouse

## Expected Behavior

Less should scroll the screen when scrolling with the mouse.

## Actual Behavior

Less is not scrolling with the mouse.

## Additional Notes

Possibly unrelated, but I have noticed that if I input `j` or `k` (the arrow keys do not exhibit this behavior) then try scrolling with the mouse it will scroll one-way only in that direction until another key is pressed (unless that other key is the opposite direction, `j` or `k`, which will then simply reverse the one-way scroll direction).

## Versions

- Windows: Windows 10 21H2 (19044.2006)
- Less: 608

**Comment by jftuga** [comment]
This is a great bug report.  However, my project simply downloads the [less source code](http://greenwoodsoftware.com/less/download.html#source) from the upstream and then uses an automated [GitHub Action](https://github.com/jftuga/less-Windows/blob/master/.github/workflows/nightly.yml) to compile the untouched source code to create the `less.exe` binary and then publish it to the [Releases](https://github.com/jftuga/less-Windows/releases) section.

Please consider posting your bug report here:

https://www.reddit.com/r/aws/comments/rx156k/the_aws_service_i_hate_the_most/

**Comment by sitiom** [comment]
This seems to be already fixed upstream in https://github.com/gwsw/less/issues/379

**Comment by jftuga** [comment]
This is great. Thank you @sitiom!  Running `less --mouse` works as expected now with version 6.43.

**Comment by jftuga** [comment]
I know this is an old, closed issue, but I wanted to point this out about the new version of `Windows Terminal`:

Source: https://github.com/microsoft/terminal/discussions/17200

* Alternate Scroll Mode is on by default, so you can scroll pagers like `less` with the mouse whee
