### ISSUE TITLE
8-bit colors not supported

### ISSUE THREAD

**Issue by ghost** [jftuga/less-Windows#40]
<https://wikipedia.org/wiki/ANSI_escape_code#8-bit>

using this Go program:

~~~go
package main

func main() {
   print("\x1b[38;5;2m+asdf\x1b[39m\n")
   print("\x1b[32m+\x1b[m\x1b[32masdf\x1b[m\n")
}
~~~

I get expected result:

![pass](https://github.com/jftuga/less-Windows/assets/126826528/0fb3b53c-5ceb-45b1-9006-091efb21a8ce)

if I write the same data to a file:

~~~go
package main

import "os"

func main() {
   f, err := os.Create("hello.txt")
   if err != nil {
      panic(err)
   }
   defer f.Close()
   f.WriteString("\x1b[38;5;2m+asdf\x1b[39m\n")
   f.WriteString("\x1b[32m+\x1b[m\x1b[32masdf\x1b[m\n")
}
~~~

Less fails with the first line:

![fail](https://github.com/jftuga/less-Windows/assets/126826528/41944cbf-e30f-484b-abd4-665fc8077bba)

~~~
> less --version
less 633 (Spencer V8 regular expressions)
~~~

**Comment by 1268** [comment]
https://github.com/martinvonz/jj/issues/1930

**Comment by sitiom** [comment]
- https://github.com/gwsw/less/issues/410#issuecomment-1664469167
> Regarding this issue, 8-bit color sequences are not supported on Windows because less uses `_settextcolor` and `_setbkcolor`, which only support 4-bit color. One solution would be to use -Da which passes SGR sequences to the terminal, if the terminal supports ENABLE_VIRTUAL_TERMINAL_PROCESSING.

![image](https://github.com/jftuga/less-Windows/assets/56180050/42f355d6-4a7e-4642-bd48-60141a4db78b)

Feel free to reopen the issue upstream if this is not the intended solution that you want.

**Comment by sitiom** [comment]
Just to note that this is now fixed as of [`less-v668`](https://github.com/jftuga/less-Windows/releases/tag/less-v668):
> - Make 256/true colors work better on Windows without -Da ([github #539](https://github.com/gwsw/less/issues/539), [github #546](https://github.com/gwsw/less/issues/546), [github #562](https://github.com/gwsw/less/issues/562)).
