### ISSUE TITLE
less for windows hangs when searching for Chinese characters

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [jftuga/less-Windows#6]
1. Open a file containing Chinese characters
2. Enter search mode by pressing /
3. Paste or enter from the keyboard Chinese character
4. Press Enter
5. Less is hanging

**Comment by jftuga** [comment]
Do you see the same problem under Linux?  Would it be possible for you to test less version 600 from http://greenwoodsoftware.com/less/download.html

I would be curious to see if this fixes the problem.

**Comment by Konstantin-Glukhov** [comment]
I just compiled version 603 of less with Microsoft VC 17 and gcc on Ubuntu. Microsoft version hangs on attempt to search for Chinese characters, the Linux version works fine.

**Comment by jftuga** [comment]
I can not help you with this problem other than to give you another suggestion. 

* Place the smallest file possible that exhibits the problem onto a GH repo.
* Take screenshot of it working under Linux
* Take screenshot of it not working under Windows
* * I would also try under both `cmd` and `powershell`
* Add this info to an already opened issues here: https://github.com/gwsw/less/issues/247

**Comment by Konstantin-Glukhov** [comment]
I updated the issue https://github.com/gwsw/less/issues/247 as you suggested. Hopefully a solution will be found, otherwise less on windows is not useful for the half of this planet :)

**Comment by Konstantin-Glukhov** [comment]
Here are the screenshots of less working on Linux:

less [Japanese.txt](https://github.com/gwsw/less/files/8367858/Japanese.txt)

<img width="135" alt="Linux-1" src="https://user-images.githubusercontent.com/24302271/160528930-dffedf25-abff-4ac6-8517-813a65b609dc.png">

Enter a search text in Japanese and hit Enter:

<img width="119" alt="Linux-2" src="https://user-images.githubusercontent.com/24302271/160529233-e8c770fb-bae2-47c8-90c1-3fe2bd0d8a80.png">

Search results are highlighted:

<img width="101" alt="Linux-3" src="https://user-images.githubusercontent.com/24302271/160529235-31f1f33c-15b4-4660-b4a9-288a5d32705c.png">

Here are the screenshots of less hanging on Windows (results are the same in both cmd.exe and PowerShell.exe):

Open a file with less:

<img width="335" alt="Windows-Cmd-1" src="https://user-images.githubusercontent.com/24302271/160530461-140e5496-32ad-41c2-be52-360e214b384e.png">
<img width="136" alt="Windows-Cmd-2" src="https://user-images.githubusercontent.com/24302271/160530463-075c9ef9-c8a4-4f07-aa6e-392ff22c3914.png">

Enter a search text in English and hit Enter:

<img width="113" alt="Windows-Cmd-3" src="https://user-images.githubusercontent.com/24302271/160530464-d6b5c63f-b5bf-429f-ab0b-e7f26434620e.png">

Search results are highlighted:

<img width="106" alt="Windows-Cmd-4" src="https://user-images.githubusercontent.com/24302271/160530465-acd3eab9-2cd2-48f9-90a3-453bd60ade31.png">

Attempt to search a text in Japanese:

<img width="118" alt="Windows-Cmd-5" src="https://user-images.githubusercontent.com/24302271/160530466-0fd934b0-d538-4d39-9e67-efe70c30ad4e.png">

After hitting "/" and entering the first Japanese character, less becomes unresponsive. After that ESC, Backspace, Ctrl-C or "q" do not work, and **less** needs to be killed from "Task Manger".

**Comment by jftuga** [comment]
[less v608](https://github.com/jftuga/less-Windows/releases/tag/less-v608) has been released.  Can you please try it?  If it does not work, you should report the bug to the upstream.

My project simply downloads the [less source code](http://greenwoodsoftware.com/less/download.html#source) from the upstream and then uses an automated [GitHub Action](https://github.com/jftuga/less-Windows/blob/master/.github/workflows/nightly.yml) to compile the untouched source code to create the `less.exe` binary and then publish it to the [Releases](https://github.com/jftuga/less-Windows/releases) section.

Please consider posting your bug report here:

https://github.com/gwsw/less/issues

**Comment by Konstantin-Glukhov** [comment]
It seems to be working as expected.
